### PR TITLE
frontend integration <#20,#30,#31> The app.js file in the frontend po…

### PR DESCRIPTION
**Pull request by satvinaik-umass**
app.js was changed so that information is gotten from the api instead of the indexdb. Frontend integration was done.

### CODE REVIEW

**Comment by nehalgarg03** [comment]
Looks good! It's good that you got rid of indexdb and used the api and database instead. Your code also has no merge conflicts so far, so that's great.

**Comment by nandapriyal2003** [comment]
The chat feature looks good and information is being fetched correctly from database too allowing users to chat seamlessly with others over their music preferences! Great Job

**Comment by aanyamehta1** [comment]
This looks great! All your frontend is integrated with the backend now, and its being fetched from the sequelite database, which is great and dynamic

**Review by sheldor1510 — APPROVED** [review]
looks good! the chat api seems well integrated!

**Pull request merged**
