### PR TITLE
Backend onaboarding 1: Fetching colleges

### LINKED ISSUE #26: [BACKEND] Onboarding-1: Set Up College List
- Description: Create a backend API endpoint or find a list of colleges. Fetch the list from an external or internal source and provide it as a JSON response.
- Tag: 
- Size Category: Small 1 point
- Owner: Priyal Nanda
- Expected Outcome: delivers a formatted college list for frontend use in json format.

### PR DESCRIPTION
**Pull request by nandapriyal2003**
Fetching College Data: I utilized the existing colleges.json file to store the list of colleges. This data is fetched and presented in the frontend as a dropdown list, allowing users to select their college from a list of available options. 

JavaScript Changes: I implemented a script to fetch the college data from the local JSON file and dynamically populate the dropdown with the available colleges. I integrated the feature so that once a college is selected, the preferences and options related to that college are filtered accordingly.

Backend Integration: The index.js file was updated to handle the college data appropriately. It ensures that the backend correctly stores the selected college when the user chooses it, and retrieves it when needed for future use.

Frontend Updates: The HTML file was updated to include a dropdown (<select>) for college selection. I added styles to ensure that the dropdown fits seamlessly within the design of the page. The text input background color was adjusted to maintain consistency with the page’s theme, and the dropdown items are displayed with proper styling.

Issues resolved: #26, #28

### CODE REVIEW

**Comment by nehalgarg03** [comment]
That sounds like a solid implementation! I really like how you utilized the college json file for storing the list of colleges—keeping the data in a structured file like that makes it easy to manage and update later. The frontend update with the dropdown looks great too.

**Comment by agunjikar** [comment]
The drop down list is very intuitive and easy to work with, and the backend correctly updates.

**Review by sheldor1510 — APPROVED** [review]
Looks good! The colleges are being fetched properly!

**Review by agunjikar — APPROVED** [review]
The drop down is very intuitive, good changes to the front end and backend both.

**Review by nehalgarg03 — COMMENTED** [review]
That sounds like a solid implementation! I really like how you utilized the college json file for storing the list of colleges—keeping the data in a structured file like that makes it easy to manage and update later. The frontend update with the dropdown looks great too.

**Review by aanyamehta1 — APPROVED** [review]
Great job! Colleges are fetched correctly and errors are handled. I really like that you adapted the styles of the dropdown to fit with the rest of the UI. Well done Priyal!

**Pull request merged**
